# CMake generated Testfile for 
# Source directory: C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests
# Build directory: C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-tiny "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-tiny.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny PROPERTIES  LABELS "tiny;gh" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;19;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-tiny "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-tiny.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny PROPERTIES  LABELS "tiny;gh" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;19;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-tiny "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-tiny.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny PROPERTIES  LABELS "tiny;gh" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;19;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-tiny "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-tiny.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny PROPERTIES  LABELS "tiny;gh" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;19;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-tiny NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-tiny.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-tiny.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny.en PROPERTIES  LABELS "tiny;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;26;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-tiny.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-tiny.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny.en PROPERTIES  LABELS "tiny;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;26;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-tiny.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-tiny.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny.en PROPERTIES  LABELS "tiny;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;26;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-tiny.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-tiny.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny.en PROPERTIES  LABELS "tiny;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;26;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-tiny.en NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-base "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-base.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;33;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-base "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-base.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;33;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-base "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-base.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;33;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-base "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-base.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;33;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-base NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-base.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-base.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base.en PROPERTIES  LABELS "base;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;40;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-base.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-base.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base.en PROPERTIES  LABELS "base;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;40;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-base.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-base.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base.en PROPERTIES  LABELS "base;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;40;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-base.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-base.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base.en PROPERTIES  LABELS "base;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;40;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-base.en NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-small "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-small.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small PROPERTIES  LABELS "small" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;47;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-small "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-small.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small PROPERTIES  LABELS "small" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;47;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-small "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-small.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small PROPERTIES  LABELS "small" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;47;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-small "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-small.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small PROPERTIES  LABELS "small" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;47;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-small NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-small.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-small.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small.en PROPERTIES  LABELS "small;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;54;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-small.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-small.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small.en PROPERTIES  LABELS "small;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;54;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-small.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-small.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small.en PROPERTIES  LABELS "small;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;54;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-small.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-small.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small.en PROPERTIES  LABELS "small;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;54;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-small.en NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-medium "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-medium.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium PROPERTIES  LABELS "medium" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;61;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-medium "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-medium.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium PROPERTIES  LABELS "medium" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;61;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-medium "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-medium.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium PROPERTIES  LABELS "medium" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;61;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-medium "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-medium.bin" "-l" "fr" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium PROPERTIES  LABELS "medium" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;61;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-medium NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-medium.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-medium.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium.en PROPERTIES  LABELS "medium;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;68;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-medium.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-medium.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium.en PROPERTIES  LABELS "medium;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;68;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-medium.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-medium.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium.en PROPERTIES  LABELS "medium;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;68;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-medium.en "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-medium.en.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium.en PROPERTIES  LABELS "medium;en" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;68;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-medium.en NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-large "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-large.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-large PROPERTIES  LABELS "large" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;75;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-large "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-large.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-large PROPERTIES  LABELS "large" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;75;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-large "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-large.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-large PROPERTIES  LABELS "large" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;75;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-large "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/models/for-tests-ggml-large.bin" "-f" "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-large PROPERTIES  LABELS "large" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;75;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-large NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-vad "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Debug/test-vad.exe")
  set_tests_properties(test-vad PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;96;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-vad "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Release/test-vad.exe")
  set_tests_properties(test-vad PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;96;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-vad "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/MinSizeRel/test-vad.exe")
  set_tests_properties(test-vad PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;96;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-vad "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/RelWithDebInfo/test-vad.exe")
  set_tests_properties(test-vad PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;96;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-vad NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-vad-full "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Debug/test-vad-full.exe")
  set_tests_properties(test-vad-full PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;104;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-vad-full "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/Release/test-vad-full.exe")
  set_tests_properties(test-vad-full PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;104;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-vad-full "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/MinSizeRel/test-vad-full.exe")
  set_tests_properties(test-vad-full PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;104;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-vad-full "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/bin/RelWithDebInfo/test-vad-full.exe")
  set_tests_properties(test-vad-full PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;104;add_test;C:/Users/shup4001.T9/Project/automatic-speech-recognition/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-vad-full NOT_AVAILABLE)
endif()
